DROP TABLE IF EXISTS car_solutions CASCADE;
DROP TABLE IF EXISTS solution_products CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS solutions CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS staging_csv CASCADE; 